-- Add columns that may be missing if tables existed before Flyway V1
ALTER TABLE trades ADD COLUMN IF NOT EXISTS position_size DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS confidence VARCHAR(50);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS risk_pct DOUBLE PRECISION DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS session VARCHAR(50);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS strategy VARCHAR(255);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS timeframe VARCHAR(50);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS user_email VARCHAR(255);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS stop_loss DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS take_profit DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS trade_type VARCHAR(10) NOT NULL DEFAULT 'LONG';
ALTER TABLE trades ADD COLUMN IF NOT EXISTS entry_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_price DOUBLE PRECISION DEFAULT 0;

-- strategies table
ALTER TABLE strategies ADD COLUMN IF NOT EXISTS win_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE strategies ADD COLUMN IF NOT EXISTS user_email VARCHAR(255);

-- journals table
ALTER TABLE journals ADD COLUMN IF NOT EXISTS strategy VARCHAR(255);
ALTER TABLE journals ADD COLUMN IF NOT EXISTS pnl DOUBLE PRECISION;
ALTER TABLE journals ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- algo_strategies table
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS symbol VARCHAR(50);
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS trade_direction VARCHAR(10);
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS entry_trigger VARCHAR(50);
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS entry_value DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS stop_loss DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS take_profit DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS position_size DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS max_active_trades INT DEFAULT 1;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS max_daily_loss DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT false;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS trading_account_id BIGINT;
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS user_email VARCHAR(255);
ALTER TABLE algo_strategies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- algo_executions table
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS algo_strategy_id BIGINT;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS trade_id BIGINT;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS symbol VARCHAR(50);
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS trade_direction VARCHAR(10);
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS entry_price DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS exit_price DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS position_size DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS pnl DOUBLE PRECISION DEFAULT 0;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS trigger_reason VARCHAR(255);
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP;
ALTER TABLE algo_executions ADD COLUMN IF NOT EXISTS user_email VARCHAR(255);
