services:
  - type: web
    name: tradeos-backend
    env: docker
    repo: https://github.com/CodeBuilderRaj-07/TradeOS-og
    region: oregon
    plan: free
    dockerfilePath: ./tradeos-backend/Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://ep-restless-dream-ajw9udtj-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_TMZP9ECG6qpb
      - key: JWT_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        value: sk-or-placeholder-replace-with-real-key
      - key: TWELVEDATA_API_KEY
        value: demo
      - key: NEWS_API_KEY
        value: placeholder-replace-with-real-key
      - key: GOLD_API_KEY
        value: free
      - key: SENDGRID_API_KEY
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

  - type: web
    name: tradeos-frontend
    env: static
    repo: https://github.com/CodeBuilderRaj-07/TradeOS-og
    region: oregon
    buildCommand: cd tradeos-frontend && npm ci && npm run build
    staticPublishPath: ./tradeos-frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://tradeos-backend.onrender.com/api
      - key: VITE_GITHUB_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        value: 160687474803-bmc3h4f32k1a3n3b77i182ke4sgjhk6r.apps.googleusercontent.com
